apiVersion: v1
kind: Service
metadata:
  name: pmodel-exporter-service
  namespace: ai-platform
  labels:
    app: pmodel-exporter-service

spec:
  ports:
    - port: 9010
      targetPort: 9010
      protocol: TCP
  type: NodePort
  selector:
    app: pmodel-exporter-service-pod

