apiVersion: v1
kind: Service
metadata:
  name: pkube-api-service
  namespace: ai-platform
  labels:
    app: pkube-api-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: pkube-api-pod
